# Generated by Django 3.2.9 on 2023-08-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('category', models.CharField(max_length=100)),
                ('image1', models.URLField(max_length=1000)),
                ('image2', models.URLField(max_length=1000)),
                ('image3', models.URLField(max_length=1000)),
                ('image4', models.URLField(max_length=1000)),
                ('image5', models.URLField(max_length=1000)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('description', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
