# Generated by Django 3.2 on 2023-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0007_auto_20230730_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
